### PR TITLE
Update Vancouver based OSS Contributor: Marriata

### PR DESCRIPTION
**Pull request by SudharakaP**
Add [Marriata](https://github.com/Mariatta) to the list. 😄

### CODE REVIEW

**Comment by kvirani** [comment]
Amazing, thank you!

**Comment by kvirani** [comment]
Welcome, @Mariatta to our humble list :)

**Comment by SudharakaP** [comment]
@kvirani : You are welcome 👍

**Comment by Mariatta** [comment]
Thanks for including me!

**Pull request merged**
